version: '3.8'

services:
  # AdonisJS v6 React starter kit
  web:
    build:
      context: ../../
      dockerfile: infra/container/Dockerfile
    container_name: adonisjs-app
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
      - PORT=3333
      - HOST=0.0.0.0
      - DATABASE_URL=surrealdb://surrealdb:8000
    depends_on:
      - surrealdb
    volumes:
      - ../../backend/uploads:/app/uploads
    networks:
      - app-network
    restart: unless-stopped

  # SurrealDB database
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    ports:
      - "8000:8000"
    environment:
      - SURREAL_USER=root
      - SURREAL_PASS=root
    volumes:
      - surrealdb_data:/data
    networks:
      - app-network
    restart: unless-stopped
    command: start --user root --pass root memory

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    networks:
      - app-network
    restart: unless-stopped

volumes:
  surrealdb_data:

networks:
  app-network:
    driver: bridge